# Site settings
title: Icon set
email: icons@tinktank.club
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: tinktankMTL
github_username:  tinktankMTL

# Build settings
markdown: kramdown

#icons 
icons: 
- title: backpack back
  png: backpackback 
  tags: 
- title: backpack front
  png: backpackfront 
  tags: 
- title: cat
  png: cat
  tags: 
- title: paint roller
  png: paintroller
  tags: 
- title: planet
  png: planet
  tags: 
- title: rose
  png: rose
  tags: 
- title: suitcase
  png: suitcase
  tags: 
- title: cocktail 
  png: cocktail
  tags:
- title: diamond
  png: diamond
  tags:
- title: fly
  png: fly
  tags:
- title: hand
  png: hand
  tags:
- title: back hand 
  png: hand2
  tags:
- title: pointed finger
  png: handpointedfinger
  tags:
- title: rocket
  png: rocket
  tags:
- title: amphora
  png: amphora
  tags:
- title: glasses
  png: glasses
  tags:
- title: handicap
  png: handicap
  tags:
- title: radio
  png: radio
  tags:
- title: signs
  png: signs
  tags:
- title: stroller
  png: stroller
  tags:
- title: ticket
  png: ticket
  tags:
- title: cake
  png: cake
  tags:
- title: glue
  png: glue
  tags:
- title: icecream
  png: icecream
  tags:
- title: measuring tape
  png: measuringtape
  tags:
- title: printer
  png: printer
  tags:
- title: tape
  png: tape
  tags:
- title: tipi
  png: tipi
  tags:
- title: usb
  png: usb
  tags:
- title: bird
  png: bird
  tags:
- title: calendar
  png: calendar
  tags:
- title: coffee
  png: coffee
  tags:
- title: garage
  png: garage
  tags:
- title: newspaper
  png: newspaper
  tags:
- title: paint
  png: paint
  tags:
- title: parcel
  png: parcel
  tags:
- title: plane
  png: plane
  tags:
- title: wood
  png: wood
  tags:
- title: bell
  png: bell
  tags:
- title: browser
  png: browser
  tags:
- title: disguise
  png: disguise
  tags:
- title: eye
  png: eye
  tags:
- title: laptop
  png: laptop
  tags:
- title: microphone
  png: microphone
  tags:
- title: music
  png: music
  tags:
- title: raspberryPi
  png: raspi
  tags:
- title: 3D printer
  png: 3Dprinter
  tags:
- title: art
  png: art
  tags:
- title: bike
  png: bike
  tags:
- title: camera
  png: camera
  tags:
- title: controller
  png: controller
  tags:
- title: mouse
  png: mouse
  tags:
- title: mug
  png: mug
  tags:
- title: wallet
  png: wallet
  tags:
- title: cone
  png: cone
  tags:
- title: dinosaur
  png: dinosaur
  tags:
- title: heart
  png: heart
  tags:
- title: medal
  png: medal
  tags:
- title: paper clip
  png: paperclip
  tags:
- title: smartphone
  png: smartphone
  tags:
- title: star
  png: star
  tags:
- title: ufo
  png: ufo
  tags:
- title: book
  png: book
  tags:
- title: map
  png: map
  tags:
- title: museum
  png: museum
  tags:
- title: oil
  png: oil
  tags:
- title: pencil
  png: pencil
  tags:
- title: pin
  png: pin
  tags:
- title: share
  png: share
  tags:
- title: ux
  png: ux
  tags:
- title: code
  png: code
  tags:
- title: speech
  png: speech
  tags:
- title: wrench
  png: wrench
  tags:








