# Site settings
title: Iconothèque
email: icons@tinktank.club
description: "A library of beautiful, hand-crafted pictograms. Oh, and they're free to use." 
baseurl: "" # the subpath of your site, e.g. /blog/ http://icons.tinktank.club
url: "http://icons.tinktank.club" # the base hostname & protocol for your site
twitter_username: tinktankMTL
github_username:  tinktankMTL
permalink: /:title

# Build settings
markdown: kramdown

#carousel welcome 
carousel: 
- map
- disguise
- radio
- trumpet

#calls-to-action
cta:
- title: Ask for an icon
  text: Is an icon missing? Fill in a form and we might just make it! We draw new icons all the time!
  icon: comment
  link: mailto:icons@tinktank.club
- title: Sponsor a set
  text: You want a complete set of icons for your project? And you want them to be available for everyone else? Drop us a line!
  icon: folder
  link: mailto:icons@tinktank.club
- title: Contribute
  text: You like playing around with vector drawings? This set of icons is collaborative. We need you to help us make more! 
  icon: edit
  link: http://icons.tinktank.club/contribute

#contributors
contributors:
- name: Arthur Schmitt
  link: http://arthurschmitt.com/
- name: Mathias Rabiot
  link: http://www.grapheine.com/

#icons 
icons: 
- title: backpack back
  png: backpackback 
  tags: 
    - school 
- title: backpack front
  png: backpackfront 
  tags: 
    - school
- title: cat
  png: cat
  tags: 
    - animals
    - nature
- title: paint roller
  png: paintroller
  tags: 
   - tools
- title: planet
  png: planet
  tags: 
   - science
- title: rose
  png: rose
  tags: 
    - nature
- title: suitcase
  png: suitcase
  tags: 
   - travel
- title: cocktail 
  png: cocktail
  tags:
   - food
- title: diamond
  png: diamond
  tags: 
   - random
- title: fly
  png: fly
  tags:
   - random
   - animals
   - nature
- title: hand
  png: hand
  tags:
   - hand
   - human
   - interaction
- title: back hand 
  png: hand2
  tags:
   - hand
   - human
   - interaction
- title: pointed finger
  png: handpointedfinger
  tags:
   - hand
   - human
   - interaction
- title: rocket
  png: rocket
  tags:
   - science
- title: amphora
  png: amphora
  tags:
   - museum
   - history
- title: glasses
  png: glasses
  tags:
- title: handicap
  png: handicap
  tags:
   - museum
- title: radio
  png: radio
  tags:
   - objects
- title: signs
  png: signs
  tags:
   - museum
- title: stroller
  png: stroller
  tags:
   - museum
   - random
- title: ticket
  png: ticket
  tags:
   - museum
   - random
- title: cake
  png: cake
  tags:
   - food
- title: glue
  png: glue
  tags:
   - tools
- title: icecream
  png: icecream
  tags:
   - summer
   - food
- title: measuring tape
  png: measuringtape
  tags:
   - tools
- title: printer
  png: printer
  tags:
   - devices
- title: tape
  png: tape
  tags:
   - tools
- title: tipi
  png: tipi
  tags:
- title: usb
  png: usb
  tags:
   - devices
- title: bird
  png: bird
  tags:
   - nature
   - animals
- title: calendar
  png: calendar
  tags:
   - organization
- title: coffee
  png: coffee
  tags:
   - food
- title: garage
  png: garage
  tags:
   - places
   - random
- title: newspaper
  png: newspaper
  tags:
   - random
- title: paint
  png: paint
  tags:
   - tools
- title: parcel
  png: parcel
  tags:
   - organization
- title: paper airplane
  png: plane
  tags:
   - random
- title: wood
  png: wood
  tags: 
   - materials
   - tools
- title: bell
  png: bell
  tags:
   - organization
- title: browser
  png: browser
  tags:
   - devices
- title: disguise
  png: disguise
  tags:
   - random
- title: eye
  png: eye
  tags:
- title: laptop
  png: laptop
  tags:
   - devices
- title: microphone
  png: microphone
  tags:
   - devices
- title: music
  png: music
  tags:
- title: raspberryPi
  png: raspi
  tags:
   - tools
   - fablab
- title: 3D printer
  png: 3Dprinter
  tags:
   - tools
   - fablab
- title: art
  png: art
  tags:
   - museum
- title: bike
  png: bike
  tags:
   - random
   - travel
   - city
- title: camera
  png: camera
  tags:
   - devices
- title: game controller
  png: controller
  tags:
   - devices
- title: mouse
  png: mouse
  tags:
   - devices
- title: mug
  png: mug
  tags:
   - food
- title: wallet
  png: wallet
  tags:
   - organization
- title: traffic cone
  png: cone
  tags:
   - city
   - random
- title: dinosaur
  png: dinosaur
  tags:
   - animals
   - science
- title: heart
  png: heart
  tags:
   - basic
- title: medal
  png: medal
  tags:
   - basic
   - museomix
- title: paper clip
  png: paperclip
  tags:
   - tools
   - office
   - museomix
- title: smartphone
  png: smartphone
  tags:
   - devices
- title: star
  png: star
  tags:
   - basic
- title: ufo
  png: ufo
  tags:
   - science
   - random
   - museomix
- title: book
  png: book
  tags:
   - basic
   - science
   - museomix
- title: map
  png: map
  tags:
   - basic
   - museum
- title: museum
  png: museum
  tags:
   - museum
- title: oil
  png: oil
  tags:
   - museomix
   - tools
- title: pencil
  png: pencil
  tags:
   - museomix
   - tools
- title: pin
  png: pin
  tags:
   - city
- title: share
  png: share
  tags:
   - museomix
   - basic
- title: ux
  png: ux
  tags:
   - museomix
   - hand
- title: code
  png: code
  tags:
   - museomix
- title: speech
  png: speech
  tags: 
   - museomix
- title: wrench
  png: wrench
  tags:
   - museomix
   - tools
- title: peace
  png: peacesign
  tags: 
  - hand
- title: desk lamp 
  png: desklamp
  tags: 
  - work
- title: drill 
  png: drill 
  tags: 
  - tools
- title: lego brick
  png: lego
  tags: 
  - playing
- title: apron
  png: apron
  tags: 
  - food
- title: barbecue 
  png: bbq
  tags: 
  - food
  - summer
  - random
- title: LEDs 
  png: leds
  tags: 
  - tools
  - fablab 
- title: hammer
  png: hammer
  tags: 
  - tools
- title: claw hammer
  png: hammer2
  tags: 
  - tools
  - random
- title: hacksaw
  png: handsaw
  tags: 
  - tools
- title: wood saw
  png: woodsaw
  tags: 
  - tools
- title: spade
  png: spade
  tags: 
  - tools
- title: ruler
  png: ruler
  tags: 
  - tools
- title: playing cards
  png: cards
  tags: 
  - playing
  - random
- title: large paintbrush
  png: lgpaintbrush
  tags: 
  - tools
- title: small paintbrush
  png: smpaintbrush
  tags: 
  - tools
- title: nuts and bolts
  png: nutsandbolts
  tags: 
  - tools
- title: circular saw
  png: circularsaw
  tags: 
  - tools
- title: scissors
  png: scissors
  tags: 
  - tools
- title: speaker
  png: speaker
  tags: 
  - music
- title: owl
  png: owl
  tags: 
  - nature
  - animals
- title: lego head
  png: legoface
  tags: 
  - playing
- title: r2d2
  png: r2d2
  tags: 
  - random
  - robot
  - starwars
  - retro
- title: sewing machine
  png: sewingmachine
  tags: 
  - tools
- title: iron
  png: iron
  tags: 
  - tools
  - random 
- title: trumpet
  png: trumpet
  tags: 
  - music
  - random
- title: turntable
  png: turntable
  tags: 
  - music
  - retro
- title: toilet paper
  png: toiletpaper
  tags: 
  - hygiene
- title: compass
  png: compass-36
  tags: 
  - tools
- title: croissant
  png: croissant
  tags: 
  - food
- title: fire hydrant 
  png: firehydrant
  tags: 
  - city
- title: lighthouse 
  png: lighthouse
  tags: 
  - building
- title: mail box
  png: mailbox
  tags: 
  - city
- title: surveillance camera  
  png: surveillance
  tags: 
  - city
- title: toothbrush 
  png: toothbrush
  tags: 
  - hygiene
- title: viewmaster
  png: viewmaster
  tags: 
  - random
  - retro
- title: suitcase with wheels
  png: wheelsuitcase
  tags: 
  - travel
- title: atom
  png: atom
  tags: 
  - science
- title: buggy
  png: buggy
  tags: 
  - kids
- title: cassette 
  png: cassette
  tags: 
  - music
  - retro
- title: coffee pot 
  png: coffeepot
  tags: 
  - food
- title: regular coffee pot 
  png: coffeepot2
  tags: 
  - food
- title: leaf 
  png: leaf
  tags: 
  - nature
- title: milk
  png: milk
  tags: 
  - food
- title: sneaker 
  png: sneaker
  tags: 
  - clothes
- title: beer can
  png: beercan
  tags: 
  - food
- title: bin 
  png: bin
  tags: 
  - 
- title: cloud
  png: cloud
  tags: 
  - nature
- title: gas station
  png: gasstation
  tags: 
  - travel
  - energy
- title: guitar
  png: guitar
  tags: 
  - music
- title: jerrican
  png: jerrican
  tags: 
  - travel
  - random
  - energy
- title: socks
  png: socks
  tags: 
  - clothes
  - random
- title: synthetiser
  png: synth
  tags: 
  - music
- title: wine glass
  png: wineglass
  tags: 
  - food
- title: dna 
  png: dna
  tags: 
  - science
- title: floppy disk
  png: floppydisk
  tags: 
  - random
  - retro
- title: knife
  png: knife
  tags: 
  - food
- title: knitting needles 
  png: knittingneedles
  tags: 
  - clothes
  - craft 
- title: lightbulb
  png: lightbulb
  tags: 
  - 
- title: mobile phone
  png: mobile
  tags: 
  - devices
- title: robot head
  png: robot
  tags: 
  - science
- title: yarn
  png: wool
  tags: 
  - craft
- title: clamp
  png: clamp
  tags: 
  - tools
- title: nyan cat
  png: nyan
  tags: 
  - random
- title: pylon
  png: pylon
  tags: 
  - city
  - energy
- title: remote control
  png: remotecontrol
  tags: 
  - fablab
- title: smart watch
  png: smartwatch
  tags: 
  - devices
- title: trojan horse
  png: trojanhorse
  tags: 
  - random
- title: typewriter
  png: typewriter
  tags: 
  - devices
  - random 
  - retro
- title: bones
  png: bones
  tags: 
  - 
- title: skull
  png: skull
  tags: 
  - 
- title: bike seat
  png: bikeseat
  tags:
    - travel
    - bike
- title: caravan
  png: caravan
  tags:
    - travel
    - habitat
- title: cutting board
  png: cuttingboard
  tags:
    - food
- title: gumball machine
  png: gumball
  tags:
  - food
  - retro
- title: horse saddle
  png: horsesaddle
  tags: 
- title: hot thermometer
  png: thermometerhot
  tags: 
    - summer
- title: tooth
  png: tooth
  tags:
  - body
- title: viking hat
  png: vikinghat
  tags:
  - museum
  - history
- title: basket ball
  png: basketball
  tags:
  - sport 
- title: drum
  png: drum
  tags:
  - music
- title: give
  png: give
  tags:
  - action
- title: maracas
  png: maracas
  tags:
  - music
- title: medieval helmet
  png: medievalhelmet
  tags:
  - museum
  - history
- title: post-it
  png: postit
  tags: 
  - work
- title: protect
  png: protect
  tags:
  - action
- title: shopping basket
  png: shoppingbasket
  tags:
- title: snorkel
  png: snorkel 
  tags:
  - summer
  - sport
- title: ambulance
  png: ambulance
  tags:
  - travel
  - emergency
- title: axe
  png: axe
  tags:
  - nature
  - xmas
- title: cherries
  png: cherries
  tags:
  - food 
  - nature
- title: cowboy hat
  png: cowboyhat
  tags:
  - clothes
  - party
- title: hot air balloon
  png: hotairballoon
  tags:
  - travel
- title: knight
  png: knight
  tags:
  - playing
  - game
  - chess
- title: piece of cake
  png: pieceofcake
  tags:
  - food 
  - xmas
- title: pills
  png: pills
  tags:
  - emergency
  - xmas
- title: teapot
  png: teapot
  tags:
  - food
- title: beehive
  png: beehive
  tags:
  - food
  - nature
- title: coffee grinder
  png: coffeegrinder
  tags:
  - food 
- title: film
  png: film
  tags:
  - devices
  - retro
- title: lunar module
  png: lunarmodule
  tags:
  - science
  - space
- title: meteorit
  png: meteorit
  tags:
  - space
  - science
- title: observatory
  png: observatory
  tags:
  - science
  - space
- title: scale
  png: scale
  tags:
  - food
- title: solar system
  png: solarsystem
  tags:
  - science
  - space
- title: sputnik
  png: sputnik
  tags:
  - retro
  - space
  - science
- title: tardis
  png: tardis
  tags:
  - random 
- title: apple
  png: apple
  tags:
  - food
  - nature
- title: band aid
  png: bandaid
  tags:
  - emergency
- title: beet
  png: beet
  tags:
  - nature 
  - food
- title: carrot
  png: carrot
  tags:
  - food
  - nature
- title: clock
  png: clock
  tags:
  - devices
- title: face
  png: face
  tags:
  - body
- title: space shuttle
  png: spaceshuttle
  tags:
  - space
  - science
- title: tree
  png: tree
  tags:
  - nature
- title: camper van
  png: campervan
  tags:
  - travel
  - nature
- title: dagger
  png: dagger
  tags:
  - museum
  - nature
- title: deckchair
  png: deckchair
  tags:
  - summer
- title: icecream cone
  png: icecreamcone
  tags: 
  - summer
  - food
- title: kinect
  png: kinect
  tags:
  - devices
  - tools
- title: kite
  png: kite
  tags:
  - summer
  - playing
- title: projector screen
  png: projectorscreen
  tags:
  - devices
  - retro
- title: stopwatch
  png: stopwatch
  tags:
  - devices
- title: watermelon
  png: watermelon
  tags:
  - nature
  - food
- title: foodtruck
  png: foodtruck
  tags:
  - food 
  - city
  - montreal
- title: monitor
  png: monitor
  tags:
  - devices
- title: pigeon
  png: pigeon
  tags:
  - nature
  - city
  - montreal
- title: skateboard
  png: skateboard
  tags:
  - travel
  - playing
- title: swimming suit
  png: swimmingsuit
  tags:
  - summer
  - clothes
- title: tanktop
  png: tanktop
  tags:
  - clothes
  - summer
- title: baby bottle
  png: babybottle
  tags:
  - food
  - baby
- title: compass 
  png: compass-96
  tags:
  - nature
- title: large leaf
  png: largeleaf
  tags:
  - nature
- title: old video camera
  png: oldvideocamera
  tags:
  - retro 
  - devices
- title: staple gun
  png: staplegun
  tags:
  - tools
  - work
- title: super 8
  png: super8
  tags:
  - devices
  - retro
- title: video camera 
  png: videocamera
  tags:
  - devices
- title: well
  png: well
  tags:
  - water
- title: binoculars
  png: binoculars
  tags:
  - nature
- title: jeep
  png: jeep
  tags:
  - nature
  - travel
- title: kayak
  png: kayak
  tags: 
  - summer
  - sport
  - nature
- title: keyboard
  png: keyboard
  tags:
  - devices
- title: mountains
  png: mountains
  tags:
  - nature
- title: paint bucket
  png: paintbucket
  tags:
  - tools
- title: safety pin
  png: safetypin 
  tags:
  - tools
- title: ship
  png: shipfront
  tags:
  - travel
- title: spray can
  png: spraycan
  tags:
  - tools
- title: ball pen
  png: ballpen
  tags:
  - tools 
  - work
- title: bath
  png: bath
  tags:
  - home
- title: blank notepad
  png: blanknotepad
  tags:
  - tools
- title: elevator
  png: elevator
  tags:
  - museum
- title: fridge
  png: fridge
  tags:
  - home
  - food
  - kitchen
- title: harddrive
  png: harddrive
  tags:
  - devices
- title: notepad
  png: notepad
  tags:
  - tools
  - work
- title: oven
  png: oven
  tags:
  - food
  - home
  - kitchen
- title: soap dispenser
  png: soapdispenser
  tags:
  - home
- title: stylus
  png: stylus
  tags:
  - devices
  - tools
- title: beer
  png: beer
  tags:
  - food
  - party
- title: bus
  png: busfront
  tags:
  - travel
  - city
- title: car
  png: carfront
  tags:
  - travel
  - city
- title: phone
  png: companyphone
  tags:
  - retro 
  - work
- title: mask
  png: mask
  tags:
  - party
- title: projector
  png: projector
  tags:
  - devices
  - work
- title: taxi
  png: taxifront
  tags:
  - travel 
  - city
- title: truck
  png: truckfront
  tags:
  - travel
  - city
- title: train
  png: trainfront
  tags:
  - travel
  - city
- title: boomarang
  png: boomarang
  tags:
  - playing
  - nature
- title: comb
  png: comb
  tags:
  - home
- title: corkscrew
  png: corkscrew
  tags:
  - xmas
  - party
- title: door handle
  png: doorhandle
  tags:
  - home
- title: electric guitar
  png: electricguitar
  tags:
  - music
- title: eye dropper
  png: eyedropper
  tags:
  - science
- title: forklift
  png: forklift
  tags:
  - travel
- title: ladder
  png: ladder
  tags:
  - tools
- title: t-bone
  png: tbone
  tags:
  - food
- title: vacuum cleaner
  png: vacuum
  tags:
  - home
- title: blender
  png: blender
  tags:
  - kitchen
  - home
  - food
- title: boots 
  png: boots
  tags:
  - xmas
  - nature
  - clothes
- title: wine bottle
  png: bottle
  tags:
  - party
  - xmas
  - food
- title: bread
  png: bread
  tags:
  - food 
- title: burger
  png: burger
  tags:
  - food
  - montreal
- title: eames chair
  png: eames
  tags:
  - home
- title: roller blades
  png: rollers
  tags:
  - travel
  - playing
- title: soda
  png: soda
  tags:
  - food
- title: butcher knife
  png: butcherknife
  tags:
  - food
  - kitchen
- title: balloon
  png: balloon
  tags:
  - party
  - xmas
- title: champagne
  png: champagne
  tags:
  - food
  - xmas
  - party
- title: cookie
  png: cookie
  tags:
  - food
  - xmas
- title: elf
  png: elf
  tags:
  - xmas
- title: fir
  png: fir
  tags:
  - nature
  - xmas
- title: party whistle
  png: partywhistle
  tags:
  - party
  - xmas
- title: santa
  png: santa
  tags:
  - xmas
- title: scarf
  png: scarf
  tags:
  - nature
  - xmas
- title: acorn
  png: acorn
  tags:
  - food
  - nature
  - xmas
- title: fireplace
  png: fireplace
  tags:
  - xmas
  - home
- title: hot tea  
  png: hottea
  tags:
  - xmas
  - food
  - home
  - kitchen
  - work
- title: knot 
  png: knot
  tags:
  - xmas
- title: lodge
  png: lodge
  tags:
  - xmas
  - habitat
- title: skidoo
  png: skidoo
  tags:
  - xmas
  - nature
- title: snowcat
  png: snowcat
  tags:
  - xmas
  - city
- title: snowman
  png: snowman
  tags:
  - xmas
- title: cold thermometer
  png: thermometercold
  tags:
  - xmas
- title: bells
  png: bells
  tags: 
  - xmas
- title: candy cane
  png: candycane
  tags: 
  - xmas
- title: holly
  png: holly
  tags: 
  - nature
  - xmas
- title: igloo
  png: igloo
  tags: 
  - xmas
  - nature
  - habitat
- title: lantern
  png: lantern
  tags: 
  - xmas 
  - nature
- title: log
  png: log
  tags: 
  - nature
  - xmas
- title: snow shoes
  png: snowshoes
  tags: 
  - nature
  - xmas
  - travel
  - montreal
- title: stocking
  png: stocking
  tags: 
  - xmas
- title: wooly hat
  png: woolyhat
  tags: 
  - xmas
  - clothes
- title: bear skin
  png: bearskin
  tags: 
  - xmas
  - home
- title: ice skates
  png: iceskates
  tags: 
  - xmas
  - playing 
  - montreal
  - sport
- title: rein deer
  png: reindeer
  tags: 
  - animals
  - xmas
  - nature
- title: ski boots
  png: skiboots
  tags: 
  - sport
  - xmas
- title: ski goggles
  png: skigoggles
  tags: 
  - sport
  - clothes
  - xmas
- title: snowflake
  png: snowflake
  tags: 
  - nature
  - xmas
- title: sweater
  png: sweater
  tags: 
  - xmas
  - clothes
- title: turkey
  png: turkey
  tags: 
  - xmas
  - food
  - kitchen
- title: wreath
  png: wreath
  tags: 
  - xmas
- title: crackers
  png: crackers
  tags: 
  - xmas
- title: gingerbread man
  png: gingerman
  tags: 
  - xmas
  - food
- title: glove
  png: glove
  tags: 
  - xmas
  - clothes
- title: gloves
  png: gloves
  tags: 
  - xmas
  - clothes
- title: nutcracker
  png: nutcracker
  tags: 
  - xmas
- title: ornament
  png: ornament
  tags: 
  - xmas
- title: present
  png: present
  tags: 
  - xmas
- title: skis
  png: skis
  tags: 
  - sport
  - xmas
- title: sledge
  png: sledge
  tags: 
  - sport
  - xmas
- title: cable car
  png: telepheric
  tags: 
  - travel
  - xmas
- title: xmas tree
  png: xmastree
  tags: 
  - xmas






